TestS2V7

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,28 +20,42 @@ jobs:
 
     - name: Authenticate Source Org
       run: |
-        response=$(curl -X POST "https://login.salesforce.com/services/oauth2/token" \
-          -d "grant_type=password" \
-          -d "client_id=${{ secrets.SF_CLIENT_ID_SOURCE }}" \
-          -d "client_secret=${{ secrets.SF_CLIENT_SECRET_SOURCE }}" \
-          -d "username=${{ secrets.SF_USERNAME_SOURCE }}" \
-          -d "password=${{ secrets.SF_PASSWORD }}" )
-
-        SF_ACCESS_TOKEN=$(echo "$response" | jq -r '.access_token')
-
-        if [ -z "$SF_ACCESS_TOKEN" ]; then
-          echo "Salesforce authentication failed."
-          exit 1
-        fi
-
-        echo "SF_ACCESS_TOKEN=$SF_ACCESS_TOKEN" >> $GITHUB_ENV
-        echo "Successfully authenticated with Salesforce."
+          response=$(curl -X POST "https://login.salesforce.com/services/oauth2/token" \
+            -d "grant_type=password" \
+            -d "client_id=${{ secrets.SF_CLIENT_ID_SOURCE }}" \
+            -d "client_secret=${{ secrets.SF_CLIENT_SECRET_SOURCE }}" \
+            -d "username=${{ secrets.SF_USERNAME_SOURCE }}" \
+            -d "password=${{ secrets.SF_PASSWORD }}" )
   
+          SF_ACCESS_TOKEN=$(echo "$response" | jq -r '.access_token')
+  
+          if [ -z "$SF_ACCESS_TOKEN" ]; then
+            echo "Salesforce authentication failed."
+            exit 1
+          fi
+  
+          echo "SF_ACCESS_TOKEN=$SF_ACCESS_TOKEN" >> $GITHUB_ENV
+          echo "Successfully authenticated with Salesforce."
 
     - name: Authenticate Target Org
       run: |
-        echo "${{ secrets.SF_TARGET_ORG_AUTH_URL }}" > authfile_target.txt
-        sf org login sfdx-url --sfdx-url-file authfile_target.txt --set-default --alias targetOrg
+            response=$(curl -X POST "https://login.salesforce.com/services/oauth2/token" \
+              -d "grant_type=password" \
+              -d "client_id=${{ secrets.SF_CLIENT_ID_TARGET }}" \
+              -d "client_secret=${{ secrets.SF_CLIENT_SECRET_TARGET }}" \
+              -d "username=${{ secrets.SF_USERNAME_TARGET }}" \
+              -d "password=${{ secrets.SF_PASSWORD_TARGET }}" )
+    
+            SF_ACCESS_TOKEN=$(echo "$response" | jq -r '.access_token')
+    
+            if [ -z "$SF_ACCESS_TOKEN" ]; then
+              echo "Salesforce authentication failed."
+              exit 1
+            fi
+    
+            echo "SF_ACCESS_TOKEN=$SF_ACCESS_TOKEN" >> $GITHUB_ENV
+            echo "Successfully authenticated with Salesforce."
+  
 
     - name: Retrieve Metadata from Source Org
       run: |
